//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeGen2DLog
    {
        public int CodeGen2DLogID { get; set; }
        public Nullable<int> Station { get; set; }
        public Nullable<int> Folio { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<System.Guid> DocumentID { get; set; }
        public string Details { get; set; }
        public string MachineName { get; set; }
        public string ClientInfo { get; set; }
    }
}
