//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeConfigurationDetail
    {
        public long ConfigurationID { get; set; }
        public short FieldID { get; set; }
        public Nullable<int> Bytes { get; set; }
        public Nullable<short> FieldTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual CodeConfiguration CodeConfiguration { get; set; }
        public virtual DataType DataType { get; set; }
    }
}
