//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodeConfiguration()
        {
            this.CodeConfigurationDetail = new HashSet<CodeConfigurationDetail>();
            this.CypherKey = new HashSet<CypherKey>();
        }
    
        public long ConfigurationID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<short> HorizontalClusters { get; set; }
        public Nullable<short> VerticalClusters { get; set; }
        public Nullable<short> RandomBytes { get; set; }
        public Nullable<short> CopiesNumber { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public short PixelRatio { get; set; }
        public int Percentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeConfigurationDetail> CodeConfigurationDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CypherKey> CypherKey { get; set; }
    }
}
