//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeImageLog
    {
        public long CodeImageLogID { get; set; }
        public int CypherKeyID { get; set; }
        public int Station { get; set; }
        public long Folio { get; set; }
        public byte[] Image { get; set; }
        public short CopyNumber { get; set; }
    }
}
