//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationDetail
    {
        public long ConfigurationDetailID { get; set; }
        public int ConfigurationID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Order { get; set; }
        public short DataTypeID { get; set; }
        public Nullable<int> Bytes { get; set; }
        public string Value { get; set; }
        public int DeviceTypeID { get; set; }
        public Nullable<bool> IsCodeConfig { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Configuration Configuration { get; set; }
        public virtual DataType DataType { get; set; }
    }
}
