//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CypherKey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CypherKey()
        {
            this.CypherKeyLog = new HashSet<CypherKeyLog>();
        }
    
        public int ID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> Station { get; set; }
        public string OperationPassword { get; set; }
        public string ConfigurationPassword { get; set; }
        public Nullable<System.DateTime> ConfigurationDate { get; set; }
        public Nullable<long> CodeConfigID { get; set; }
        public Nullable<int> CypherConfigID { get; set; }
        public short Status { get; set; }
        public Nullable<long> CurrentCounter { get; set; }
        public int MaximumCounter { get; set; }
        public Nullable<long> RemainingFolios { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public int InitialCounter { get; set; }
        public Nullable<System.DateTime> Caducity { get; set; }
        public string HW_Version { get; set; }
        public string FW_Version { get; set; }
    
        public virtual CodeConfiguration CodeConfiguration { get; set; }
        public virtual CypherKeyConfiguration CypherKeyConfiguration { get; set; }
        public virtual CypherKeyStatus CypherKeyStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CypherKeyLog> CypherKeyLog { get; set; }
    }
}
