//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CypherKeyLog
    {
        public long LogID { get; set; }
        public int CypherKeyID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<long> CurrentCounter { get; set; }
        public short StatusID { get; set; }
        public Nullable<short> OperationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<long> CodeConfigurationID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string HW_Version { get; set; }
        public string FW_Version { get; set; }
    
        public virtual CypherKey CypherKey { get; set; }
    }
}
