//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int EventLogID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public string ProfileName { get; set; }
        public int OperationID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string UserLogin { get; set; }
        public Nullable<int> ApplicationID { get; set; }
    }
}
