//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mAssignations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mAssignations()
        {
            this.dAssignationDevice = new HashSet<dAssignationDevice>();
        }
    
        public int AssignationID { get; set; }
        public System.DateTime AssignationDate { get; set; }
        public System.DateTime MaxDeliveryDate { get; set; }
        public string Comment { get; set; }
        public int AssignedUserID { get; set; }
        public int OwnerUserID { get; set; }
        public string AssignationTicketID { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dAssignationDevice> dAssignationDevice { get; set; }
        public virtual mStatus mStatus { get; set; }
    }
}
