//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mDevolutions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mDevolutions()
        {
            this.dDevolutionDevice = new HashSet<dDevolutionDevice>();
        }
    
        public int DevolutionID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Comment { get; set; }
        public int OwnerUserID { get; set; }
        public int UserID { get; set; }
        public string DevolutionTicketID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dDevolutionDevice> dDevolutionDevice { get; set; }
    }
}
