//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mDevices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mDevices()
        {
            this.dAssignationDevice = new HashSet<dAssignationDevice>();
            this.dAssignationDevice1 = new HashSet<dAssignationDevice>();
            this.mDevices1 = new HashSet<mDevices>();
        }
    
        public int DeviceID { get; set; }
        public string Serial { get; set; }
        public int DeviceTypeID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ParentDeviceID { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public Nullable<System.DateTime> WarrantyDate { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dAssignationDevice> dAssignationDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dAssignationDevice> dAssignationDevice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mDevices> mDevices1 { get; set; }
        public virtual mDevices mDevices2 { get; set; }
        public virtual mDeviceTypes mDeviceTypes { get; set; }
        public virtual mStatus mStatus { get; set; }
    }
}
