//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesDeviceDomainCore : DbContext
    {
        public EntitiesDeviceDomainCore()
            : base("name=EntitiesDeviceDomainCore")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodeConfiguration> CodeConfiguration { get; set; }
        public virtual DbSet<CodeConfigurationDetail> CodeConfigurationDetail { get; set; }
        public virtual DbSet<CodeDataLog> CodeDataLog { get; set; }
        public virtual DbSet<CodeGen2DLog> CodeGen2DLog { get; set; }
        public virtual DbSet<CodeImageLog> CodeImageLog { get; set; }
        public virtual DbSet<Configuration> Configuration { get; set; }
        public virtual DbSet<ConfigurationDetail> ConfigurationDetail { get; set; }
        public virtual DbSet<CypherKey> CypherKey { get; set; }
        public virtual DbSet<CypherKeyConfigLog> CypherKeyConfigLog { get; set; }
        public virtual DbSet<CypherKeyConfiguration> CypherKeyConfiguration { get; set; }
        public virtual DbSet<CypherKeyLog> CypherKeyLog { get; set; }
        public virtual DbSet<CypherKeyStatus> CypherKeyStatus { get; set; }
        public virtual DbSet<dAssignationDevice> dAssignationDevice { get; set; }
        public virtual DbSet<DataType> DataType { get; set; }
        public virtual DbSet<dDevolutionDevice> dDevolutionDevice { get; set; }
        public virtual DbSet<EventLog> EventLog { get; set; }
        public virtual DbSet<mAssignations> mAssignations { get; set; }
        public virtual DbSet<mDevices> mDevices { get; set; }
        public virtual DbSet<mDeviceTypes> mDeviceTypes { get; set; }
        public virtual DbSet<mDevolutions> mDevolutions { get; set; }
        public virtual DbSet<mProjects> mProjects { get; set; }
        public virtual DbSet<mStatus> mStatus { get; set; }
        public virtual DbSet<mStatusTypes> mStatusTypes { get; set; }
        public virtual DbSet<mTerritory> mTerritory { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Project_LastZippedRequets> Project_LastZippedRequets { get; set; }
        public virtual DbSet<QrCodeGenLog> QrCodeGenLog { get; set; }
        public virtual DbSet<WPSTypes> WPSTypes { get; set; }
        public virtual DbSet<WPA> WPA { get; set; }
        public virtual DbSet<WPS> WPS { get; set; }
    }
}
