//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QrCodeGenLog
    {
        public long QrCodeGenLogID { get; set; }
        public string QrData { get; set; }
        public int UserID { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public byte QrVersion { get; set; }
        public string QrCodeErrorCorrection { get; set; }
        public string QrCodeEncoding { get; set; }
        public Nullable<System.Guid> ObjectGUID { get; set; }
        public string Comment { get; set; }
    }
}
