//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WPA
    {
        public int WPSID { get; set; }
        public System.DateTime ExpirationFile { get; set; }
        public int AuthorizedMaxFolios { get; set; }
        public System.DateTime AuthorizedExpiration { get; set; }
        public System.DateTime ApplyDate { get; set; }
    }
}
